name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo nextest run

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo +nightly fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy -- -D warnings

  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@nightly
          with:
            components: llvm-tools-preview
        - uses: taiki-e/install-action@cargo-llvm-cov
        - uses: Swatinem/rust-cache@v2

        - name: Coverage Summary
          run: cargo llvm-cov --workspace --all-features --summary-only --fail-under-lines 80

        - name: Generate lcov
          run: cargo llvm-cov report --lcov --output-path lcov.info
        - uses: actions/upload-artifact@v4
          with:
            name: lcov
            path: lcov.info
        - uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: lcov.info
            fail_ci_if_error: false
